name: "dbt_project"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_project"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models", "sources"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Variables that can reference environment variables
vars:
  database_name: "{{ env_var('DATABASE_NAME', 'local.duckdb') }}"
  source_data_path: "{{ env_var('SOURCE_DATA_PATH', '../datasets') }}"

# Configuring models
models:
  dbt_project:
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ["intermediate"]
    mart:
      +materialized: table
      +schema: mart
      +tags: ["mart"]
    report:
      +materialized: table
      +schema: report
      +tags: ["report"]
