dbt_project: # This matches the "profile" setting in your dbt_project.yml
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: "../{{ env_var('DATABASE_NAME', 'dev.duckdb') }}"
      threads: 4
    prod:
      type: duckdb
      path: "../{{ env_var('DATABASE_NAME')}}"
      threads: 4
