name: dbt_ci

env:
  PYTHONUNBUFFERED: "1"

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      # ------------------------- DEV (pull-request) -------------------------
      - name: Run DEV pipeline
        if: ${{ github.event_name == 'pull_request' }}
        run: make ENVIRONMENT=dev

      # ------------------------- PROD (main) -------------------------------
      - name: Run PROD pipeline
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: make ENVIRONMENT=prod

      # ---------------------- Generate dbt docs (PROD only) ----------------
      - name: Generate docs
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: make ENVIRONMENT=prod dbt-docs

      # ---------------------- store DuckDB file ----------------------------
      - name: Upload DuckDB
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev.duckdb' || 'prod.duckdb' }}
          path: ${{ github.event_name == 'pull_request' && 'dev.duckdb' || 'prod.duckdb' }}
          retention-days: 7

      # ---------------------- store dbt artefacts ---------------------------
      - name: Upload dbt target folder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dbt-target
          path: dbt_project/target/

      # ---------------------- Deploy docs to GitHub Pages ------------------
      - name: Setup Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: dbt_project/target/

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print documentation URL
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          echo "dbt documentation has been deployed!"
          echo "📚 View your docs at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          echo "🔗 Direct link: ${{ steps.deployment.outputs.page_url }}"
